"""change type in tables

Revision ID: 7979edaf7d73
Revises: 35403d57c57e
Create Date: 2026-04-01 14:25:25.035248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7979edaf7d73"
down_revision: Union[str, Sequence[str], None] = "35403d57c57e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "idempotency_key",
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "payments",
        "amount",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
        postgresql_using="amount::numeric(10,2)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments",
        "amount",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        postgresql_using="amount::varchar(20)"
    )
    op.alter_column(
        "orders",
        "idempotency_key",
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="idempotency_key::uuid"
    )
    # ### end Alembic commands ###
