"""fix_outbox_case

Revision ID: bec8579ee5ea
Revises: e648c77a44a3
Create Date: 2026-04-01 21:01:18.382478

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bec8579ee5ea"
down_revision: Union[str, Sequence[str], None] = "e648c77a44a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE outbox SET event_type = LOWER(event_type)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE outbox SET event_type = UPPER(event_type)")
    # ### end Alembic commands ###
